### ISSUE TITLE
Notice: Two-Factor Authentication

### ISSUE THREAD

**Issue by sindresorhus** [avajs/meta#1]
I plan on soon [enforcing 2FA](https://help.github.com/articles/requiring-two-factor-authentication-in-your-organization/) on the AVA organization. This is to protect the org against any single user account being hacked and doing damage in a repo.

@AlbertoFuente @charbelrami @forresst @jacobmendoza @preco21 @sohje @spudly @twada @zhaozhiming Would be wonderful if you could start using 2FA on your GitHub account.

Read how here: https://help.github.com/articles/about-two-factor-authentication/

**Comment by jfmengels** [comment]
Great idea!

**Comment by charbelrami** [comment]
Done! :)

**Comment by jacobmendoza** [comment]
Hey folks! :)

Done here too!.

**Comment by preco21** [comment]
Good call! I'll apply it soon!

**Comment by twada** [comment]
done 👍

**Comment by preco21** [comment]
Done here!

**Comment by sindresorhus** [comment]
ping @AlbertoFuente @forresst @sohje @spudly @zhaozhiming

**Comment by forresst** [comment]
oups. done

**Comment by sohje** [comment]
Yay, done.

**Comment by sindresorhus** [comment]
Alright. I've flipped the switched.

-

@AlbertoFuente @zhaozhiming Happy to add you back when you've activated 2FA ;)
